apiVersion: v2
name: qbittorrent
description: qBittorrent Helm chart
type: application
version: 0.1.20
appVersion: "5.2.3_v2.0.13-ls469"
annotations:
  version-source: github-release:linuxserver/docker-qbittorrent
