apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" . }}
  {{- if .Values.namespaceOverride }}
  namespace: {{ .Values.namespaceOverride }}
  {{- end }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.http.server_port }}
      protocol: TCP
      name: http
  selector:
    {{- include "home-assistant.selectorLabels" . | nindent 4 }}
