apiVersion: v2
name: pocket-id
description: Pocket ID Helm chart
type: application
version: 0.1.3
appVersion: "2.6.2"
annotations:
  version-source: github-release:pocket-id/pocket-id
  version-pattern: "s|^v||"
