apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "frigate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "frigate.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: rtsp
      port: {{ .Values.service.rtspPort }}
      targetPort: rtsp
      protocol: TCP
    - name: webrtc-tcp
      port: {{ .Values.service.webrtcPort }}
      targetPort: webrtc
      protocol: TCP
    - name: webrtc-udp
      port: {{ .Values.service.webrtcPort }}
      targetPort: webrtc-udp
      protocol: UDP
