apiVersion: v2
name: gitea-mirror
description: Gitea Mirror Helm chart
type: application
version: 0.1.24
appVersion: "3.22.0"
annotations:
  version-source: github-release:RayLabsHQ/gitea-mirror
  version-pattern: "s|^v||"
