apiVersion: v2
name: gitea-mirror
description: Gitea Mirror Helm chart
type: application
version: 0.1.35
appVersion: "3.32.1"
annotations:
  version-source: github-release:RayLabsHQ/gitea-mirror
  version-pattern: "s|^v||"
