apiVersion: v2
name: ntfy
description: ntfy push notification server Helm chart
type: application
version: 0.1.7
appVersion: "2.26.3"
annotations:
  version-source: github-release:binwiederhier/ntfy
  version-pattern: "s|^v||"
