apiVersion: v2
name: home-assistant-dev
description: Home Assistant development build - wraps home-assistant chart with dev defaults
type: application
annotations:
  version-source: dockerhub-dev:homeassistant/home-assistant:^[0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]+$
version: 0.1.13-dev
appVersion: "2026.4.0.dev202603240309"
dependencies:
  - name: home-assistant
    version: ">=0.1.0"
    repository: "file://../home-assistant"
