apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rtorrent-config
  namespace: {{ .Release.Namespace }}
data:
  rtorrent.rc: |
    session.path.set = /config/session/
    directory.default.set = /data
    network.scgi.open_local = /config/rtorrent.sock
    network.port_range.set = {{ .Values.torrentPort }}-{{ .Values.torrentPort }}
    network.port_random.set = no
    network.max_open_files.set = 600
    network.max_open_sockets.set = 300
