apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: torrent
  annotations:
    version-source: {{ index .Chart.Annotations "version-source" }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.webuiPort }}
              name: webui
            - containerPort: {{ .Values.rpcPort }}
              name: rpc
            - containerPort: {{ .Values.torrentPort }}
              name: torrent-tcp
              protocol: TCP
            - containerPort: {{ .Values.torrentPort }}
              name: torrent-udp
              protocol: UDP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config
        - name: data
          hostPath:
            path: {{ .Values.volumes.data.hostPath }}
            type: DirectoryOrCreate
