apiVersion: v2
name: home-assistant
description: A Helm chart for Home Assistant with PostgreSQL backup support
type: application
annotations:
  version-source: github-release:home-assistant/core
  version-pattern: "s|^v||"
version: 0.1.24
appVersion: "2026.4.4"
