apiVersion: v2
name: home-assistant-mcp
description: Home Assistant MCP server Helm chart
type: application
version: 0.2.1
appVersion: "7.3.0"
annotations:
  version-source: github-release:homeassistant-ai/ha-mcp
  version-pattern: "s|^v||"
