{{- if .Values.persistence.data.enabled }}
{{- if eq .Values.persistence.data.type "pvc" }}
{{- if not .Values.persistence.data.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "garage.fullname" . }}-data
  labels:
    {{- include "garage.labels" . | nindent 4 }}
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    {{- toYaml .Values.persistence.data.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
---
{{- if .Values.persistence.meta.enabled }}
{{- if eq .Values.persistence.meta.type "pvc" }}
{{- if not .Values.persistence.meta.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "garage.fullname" . }}-meta
  labels:
    {{- include "garage.labels" . | nindent 4 }}
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    {{- toYaml .Values.persistence.meta.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.meta.size | quote }}
  {{- if .Values.persistence.meta.storageClass }}
  storageClassName: {{ .Values.persistence.meta.storageClass | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
