apiVersion: v1
kind: Service
metadata:
  name: {{ include "garage.fullname" . }}
  labels:
    {{- include "garage.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "garage.selectorLabels" . | nindent 4 }}
  ports:
    - name: s3-api
      port: {{ .Values.service.s3ApiPort }}
      targetPort: s3-api
      protocol: TCP
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
    {{- if .Values.garage.web.enabled }}
    - name: s3-web
      port: {{ .Values.service.s3WebPort }}
      targetPort: s3-web
      protocol: TCP
    {{- end }}
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
