apiVersion: v2
name: rflood
description: rTorrent + Flood (hotio/rflood) Helm chart
type: application
version: 0.1.9
appVersion: "release-51028c6"
annotations:
  version-source: ghcr-tags-build:hotio/rflood:^release-[a-f0-9]+-[0-9]+-linux-amd64$
