# Default values for rflood Helm Chart (jesec/rtorrent-flood)
image:
  repository: jesec/rtorrent-flood
  pullPolicy: IfNotPresent

webuiPort: 3001
torrentPort: 50000

service:
  type: ClusterIP
  externalTrafficPolicy: ""
  nodePorts:
    webui: null
    torrentTcp: null
    torrentUdp: null

securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

env: {}

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "2"
    memory: "4Gi"

livenessProbe:
  enabled: true
  httpGet:
    path: /
    port: 3001
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

persistence:
  config:
    size: 2Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce

volumes:
  data:
    hostPath: ""

nodeSelector: {}
tolerations: []
affinity: {}

ingresses: {}
  # https:
  #   host: rflood.example.com
  #   annotations: {}
  #   tls:
  #     - hosts:
  #         - rflood.example.com
