apiVersion: v2
name: adguardhome
description: AdGuard Home DNS server Helm chart
type: application
version: 0.1.5
appVersion: "0.107.78"
annotations:
  version-source: github-release:AdguardTeam/AdGuardHome
  version-pattern: "s|^v||"
