apiVersion: v2
name: jellyfin
description: A Helm chart for Jellyfin media server with Postgres support
type: application
annotations:
  version-source: github-release:jellyfin/jellyfin
  version-pattern: "s|^v||"
version: 0.1.13
appVersion: "10.11.6"
