apiVersion: v2
name: mikrotik-mcp
description: MikroTik MCP server Helm chart
type: application
version: 0.1.0
appVersion: "0.5.0.0"
annotations:
  version-source: github-release:jeff-nasseri/mikrotik-mcp
  version-pattern: "s|^v||"
