apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: webui
      port: {{ .Values.webuiPort }}
      targetPort: {{ .Values.webuiPort }}
      protocol: TCP
    - name: torrent-tcp
      port: {{ .Values.torrentPort }}
      targetPort: {{ .Values.torrentPort }}
      protocol: TCP
    - name: torrent-udp
      port: {{ .Values.torrentPort }}
      targetPort: {{ .Values.torrentPort }}
      protocol: UDP
